import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#cbc6bb",
        "secondary-fixed": "#ffdf9e",
        "on-secondary": "#3f2e00",
        "secondary-fixed-dim": "#eac16a",
        "secondary": "#eac16a",
        "on-primary-fixed": "#1e1c10",
        "surface-container-lowest": "#0f0e0d",
        "outline": "#949086",
        "surface-variant": "#363433",
        "inverse-primary": "#625e4f",
        "secondary-container": "#705300",
        "error-container": "#93000a",
        "tertiary-container": "#ffdad3",
        "primary": "#ffffff",
        "surface-dim": "#141312",
        "primary-fixed": "#e9e2cf",
        "tertiary": "#ffffff",
        "tertiary-fixed": "#ffdad3",
        "surface-container-highest": "#363433",
        "primary-fixed-dim": "#cdc6b4",
        "surface-container-high": "#2b2a28",
        "on-tertiary": "#5e170b",
        "surface": "#141312",
        "inverse-surface": "#e6e2df",
        "on-primary-container": "#696455",
        "on-surface": "#e6e2df",
        "on-secondary-fixed-variant": "#5b4300",
        "surface-tint": "#cdc6b4",
        "on-tertiary-fixed": "#3f0300",
        "on-tertiary-fixed-variant": "#7c2d1f",
        "on-background": "#e6e2df",
        "error": "#ffb4ab",
        "primary-container": "#e9e2cf",
        "surface-container": "#201f1e",
        "surface-container-low": "#1c1b1a",
        "on-secondary-fixed": "#261a00",
        "on-secondary-container": "#f1c870",
        "on-primary-fixed-variant": "#4a4739",
        "surface-bright": "#3a3937",
        "inverse-on-surface": "#31302f",
        "on-tertiary-container": "#a24939",
        "on-error-container": "#ffdad6",
        "background": "#15181D", // Ink
        "outline-variant": "#49473e",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#ffb4a6",
        "on-primary": "#333024",
        "paper": "#EDE6D3",
        "brass": "#B4903E",
        "rust": "#9C4535",
      },
      borderRadius: {
        DEFAULT: "0",
        none: "0",
        sm: "0",
        md: "0",
        lg: "0",
        xl: "0",
        "2xl": "0",
        "3xl": "0",
        full: "0",
      },
      spacing: {
        indent: "24px",
        "line-separator": "1px",
        gutter: "32px",
        unit: "4px",
        "margin-page": "64px",
      },
      fontFamily: {
        "code-block": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "display-lg": ["Newsreader", "serif"],
        "headline-md": ["Newsreader", "serif"],
        "body-lg": ["JetBrains Mono", "monospace"],
        "body-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "code-block": [
          "16px",
          { lineHeight: "1.8", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "display-lg": [
          "56px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "1.4", fontWeight: "400" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", fontWeight: "400" },
        ],
        "body-sm": [
          "14px",
          { lineHeight: "1.5", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
